# This is a basic workflow to help you get started with Actions

name: Continous Integration

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - develop
      - release/*
    tags-ignore:
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch origin +refs/heads/*:refs/remotes/origin/* --unshallow --tags

    - name: CouchDB Setup
      run: docker-compose -f docker-compose-test.yml up -d
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    
    - name: Build
      run: dotnet build ./src/DistLockNet.sln --configuration Release
    
    - name: Test
      run: dotnet test ./src/DistLockNet.sln
